language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - composer install --no-interaction

before_script:
  - php artisan key:generate
  - cp .env.example .env

script:
  - vendor/bin/phpunit